version: "3.9"  # optional since v1.27.0

services:
  php-env:
    build: .
    ports:
      - "8000:80"
    depends_on:
    - mysql_db
    volumes:
      - ./src:/var/www/html
      
  mysql_db:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mysql_db
    restart: always
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1